name: Deploy Site

on:
  push:
    branches:
      - "prod"
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-node@master
      with:
        node-version: "18.11.x"
    - run: yarn
    - run: npm run deploy
    environment:
      name: github-pages
      url: ${{ steps.build-publish.outputs.page_url }}
